from pydantic import BaseModel, Field, validator
from datetime import date
from typing import List
from datetime import date, timedelta

class MovieCreateSchema(BaseModel):
    name: str = Field(..., max_length=255, description="Name of the movie")
    release_date: date = Field(..., description="Release date of the movie")
    score: float = Field(..., ge=0, le=100, description="Movie rating score (0-100)")
    overview: str = Field(..., description="Short description or synopsis of the movie")
    status: str = Field(..., pattern="^(Released|Post Production|In Production)$", description="Production status")
    budget: float = Field(..., ge=0, description="Budget of the movie (non-negative)")
    revenue: float = Field(..., ge=0, description="Revenue generated by the movie (non-negative)")
    country: str = Field(..., pattern="^[A-Z]{3}$", description="ISO 3166-1 alpha-3 country code")
    genres: List[str] = Field(..., description="List of genres")
    actors: List[str] = Field(..., description="List of actors")
    languages: List[str] = Field(..., description="List of languages")

    @validator("release_date")
    def validate_date(cls, value):
        if value > date.today() + timedelta(days=365):
            raise ValueError("The date must not be more than one year in the future.")
        return value